# Generated by Django 3.0.8 on 2020-08-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('message', models.TextField(default='', max_length=500)),
                ('schedule_meeting', models.DateField()),
                ('submition_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
