# Generated by Django 3.0.8 on 2020-08-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('lang', 'Language'), ('frmwk', 'Framework'), ('db', 'Database'), ('styl', 'Styling')], default='lang', max_length=100, verbose_name='Skill Type'),
        ),
    ]
