# Generated by Django 3.0.8 on 2020-08-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='schedule_meeting',
        ),
    ]
